name: Run Powershell Script to update Gist

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build-and-deploy:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    - name: 'Run Script'
      shell: pwsh
      run: .\FQDN_to_IP.ps1
    - name: switching from HTTPS to SSH
      run: git remote set-url origin git@github.com:tonytech95/SFX_Stage_Sites.git
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add ipaddresses.txt
    - name: commit changed files
      run: git commit -m "Auto updating ipaddress.txt"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
