name: Run Powershell Script to update Gist

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build-and-deploy:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    - name: 'Run Script'
      shell: pwsh
      run: .\FQDN_to_IP.ps1
    - name: 'Run git actions'
      run: |
        git remote set-url origin ${{ github.repositoryUrl }}
        git status
        git add ipaddresses.txt
        git config user.email "tony.yu@techordia.com"
        git config user.name "Tony Yu"
        git commit -m "Auto updating ipaddress.txt"
        git fetch origin master
        git push origin HEAD:master
