name: Run Powershell Script to update Gist

on:
  schedule:
    - cron: "*/5 * * * *"


jobs:
  build-and-deploy:
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    runs-on: windows-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    - name: 'Run Script'
      shell: pwsh
      run: .\FQDN_to_IP.ps1
    - name: 'Run git actions'
      uses: stefanzweifel/git-auto-commit-action@v5
